### ISSUE TITLE
Admin values and street numbers not used in autocomplete endpoint?

### ISSUE THREAD

**Issue by hannesj** [pelias/api#370]
When searching for `Hämeenkatu 1, Tampere`, I get mostly results that are in Turku. It seems that the confidence for all street numbers in both cities are equal, even tough the name of the city, as well as the street number have been specified in the query.

The endpoint is available at http://dev.digitransit.fi/pelias/v1/autocomplete?text=H%C3%A4meenkatu%201,%20Tampere

the results for the query can be found at https://gist.github.com/hannesj/6494e063272141512eda

**Comment by missinglink** [comment]
thanks for the feedback, I have labelled this issue for an IRL group discussion next week

**Comment by hannesj** [comment]
@missinglink, did you get to any conclusions during the discussion?

**Comment by missinglink** [comment]
hi @hannesj sorry for the delay on this one!

I'm having another look at this now for our [autocomplete improvements milestone](https://github.com/pelias/api/milestones/Autocomplete%20Improvements)

Currently on our production servers I'm getting:

```javascript
/v1/autocomplete?text=Hämeenkatu 1, Tampere

1)	1 Hämeenkatu, Tampere, Finland
2)	1 Hämeenkatu, Tampere, Finland
3)	Hämeenkatu 1, Turku, Finland
4)	1 Hämeenkatu, Turku, Finland
5)	1 Hämeenkatu, RiihimÃ¤ki, Finland
```

and on the dev cluster I'm getting:

```javascript
/v1/autocomplete?text=Hämeenkatu 1, Tampere

1)	1 Hämeenkatu, Tampere, Finland
2)	1 Hämeenkatu, Tampere, Finland
3)	Hämeenkatu 1, Turku, Finland
4)	1 Hämeenkatu, Riihimäki, Finland
5)	1 Hämeenkatu, Turku, Finland
```

Is this 'just fixed' now?

**Comment by missinglink** [comment]
regression test added https://github.com/pelias/acceptance-tests/pull/196

**Comment by hannesj** [comment]
@missinglink seems to work much better now than when this was opened. However, the comma is still needed, as there is no result without it (see [this](http://dev.digitransit.fi/pelias/v1/autocomplete?text=H%C3%A4meenkatu%201%20Tampere)), but that is taken care of in other issues.

**Comment by hannesj** [comment]
Ok, It still doesn't work properly with street numbers. See http://dev.digitransit.fi/pelias/v1/autocomplete?text=H%C3%A4meenkatu%201

**Comment by hannesj** [comment]
Also, see pelias/openstreetmap#68

**Comment by missinglink** [comment]
Nice, glad this is fixed. The number ordering issue you mentioned above it actually part of my work for this week so I'll get to that shortly.

Would you be interested in adding some other country codes which use `{street_name}, {number}` instead of `{number}, {street_name}` in [here](https://github.com/pelias/api/blob/master/middleware/localNamingConventions.js#L16)? I only configured it to flip the labels in Germany for now.

**Comment by hannesj** [comment]
Done in #453

**Comment by missinglink** [comment]
Awesome! what's the status of this ticket, can we close it now?

**Comment by hannesj** [comment]
@missinglink It still doesn't seem to work properly, see [this](http://pelias.github.io/compare/#/v1/autocomplete%3Ftext=H%C3%A4meenkatu%201). Also there seems to be a regression, as [Hämeenkatu 1, Turku](http://pelias.github.io/compare/#/v1/autocomplete%3Ftext=H%C3%A4meenkatu%201,%20Turku) only produces results in Tampere and not any in Turku :cry:

**Comment by orangejulius** [comment]
Hey all,
This looks to be mostly fixed now (Hämeenkatu 1 shows up second in an autocomplete query, but that's not too bad, and it goes away if you add a comma). If we missed something, please feel free to reopen this issue and let us know!
![screenshot_2016-07-21_11-21-52](https://cloud.githubusercontent.com/assets/111716/17028393/73dbadc8-4f35-11e6-92e8-170a8eaa12f5.png)
![screenshot_2016-07-21_11-21-38](https://cloud.githubusercontent.com/assets/111716/17028394/73dfdeac-4f35-11e6-987c-f66152081a10.png)
![screenshot_2016-07-21_11-21-18](https://cloud.githubusercontent.com/assets/111716/17028395/73e358ca-4f35-11e6-9fad-06e27d20adc1.png)

**Comment by hannesj** [comment]
Thanks!
